---
- name: Deploy Images to Swift
  hosts: localhost
  tasks:
    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: <YOUR_FILE_PATH>/terraform

    - name: Plan Terraform deployment
      command: terraform plan -out=tfplan
      args:
        chdir: <YOUR_FILE_PATH>/terraform

    - name: Apply Terraform to upload images
      command: terraform apply -auto-approve tfplan
      args:
        chdir: <YOUR_FILE_PATH>/terraform