---
- name: Deploy Namespace adtech
  hosts: localhost
  tasks:
    - name: Create adtech namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: adtech

